import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LiffProvider from "@/components/liff"; // บรรทัดที่เพิ่มเข้ามา
import LiffInitProvider from "@/components/liff/liff-init-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LiffProvider>
          <LiffInitProvider>{children}</LiffInitProvider>
        </LiffProvider>
      </body>
    </html>
  );
}
